### ISSUE TITLE
Android notifcation player doesn't go away

### ISSUE THREAD

**Issue by samyachour** [tlenclos/react-native-audio-streaming#49]
When I close my app with app switcher (in android) the notifcation player doesn't go away, and the little 'x' button doesn't work.

I found a workaround though, just for everyone's information. In my android project I made a new service and used the method onTaskRemoved which gets called when the app is closed from the app switcher.

In that method I cancelled all the notifcations for the app, and voila! Will give more info if requested.

**Comment by tlenclos** [comment]
Thanks for the tip, feel free to submit a PR if you want ;)

**Comment by IndrekV** [comment]
@samyachour I would be very interested in a more detailed explanation of the fix. I'm faced with the same issue and my Android knowledge is lacking to find the fix myself.

**Comment by samyachour** [comment]
@IndrekV no problem. I don't have much android knowledge either, so forgive my lack of depth in the explanation. But essentially we are creating a service (a background task) that will delete all notifications from the app when it's closed via the app switcher.

1. Create a file under _app/java/com.project-name_ called MyService.java, copy and paste the following code into it

`package com.chapmanradiorn;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;
import android.util.Log;
import android.app.NotificationManager;
import android.content.Context;

import com.audioStreaming.ReactNativeAudioStreamingModule;

public class MyService extends Service {

    private static final String TAG = MyService.class.getSimpleName();

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        super.onTaskRemoved(rootIntent);
        NotificationManager nMgr = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        nMgr.cancelAll();
    }

}`

Now we have a service that will remove all notifications once the app is removed from the app switcher. You probably should rename the service for code clarity. The next step is simply iniating the service when the app starts.

2. Open your MainActivity.java in the same folder. Add the following method to the public MainActivity Class.

`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate()");
        Intent serviceIntent = new Intent(this, MyService.class);
        startService(serviceIntent);
    }`

This calls our service when the app starts, as well as the rest of the stuff we need to call. Then just add these import lines to MainActivity.java and you should be good.

`import android.os.Bundle;
import android.util.Log;
import android.content.Intent;`

Let me know if you have any more questions!

**Comment by IndrekV** [comment]
@samyachour Thank you for the fast response. I tried the your suggested solution and sadly it did not work for me. I looked a bit more into the code and found that the issue was even simpler. I created PR to fix this issue #74. I hope @tlenclos merges this fast as it is pretty annoying bug.

**Comment by tlenclos** [comment]
Fixed with https://github.com/tlenclos/react-native-audio-streaming/releases/tag/v2.3.2, thanks.

**Comment by jerodb** [comment]
@tlenclos this is not fixed. #74 doesn't fix the problem. But the solution @samyachour propose works perfect.

**Comment by nusson** [comment]
@samyachour 
please add a final step to your fix :

3- Finally add the service in the app's AndroidManifest.xml (android/app/src/main) like this:
<service android:name="com.project-name.MyService" android:stopWithTask="false" />
(inside <application> )

**Comment by samyachour** [comment]
@nusson added!

Haven't looked at this in a while, but your suggestion makes sense.
